language: node_js
sudo: false
node_js:
  - 8

cache:
  yarn: true
  directories:
    - .eslintcache
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn run clean
  - yarn run build
  - yarn lint:cached
  - yarn test
